[package]
name = "crab-pi"
version = "0.1.0"
edition = "2024"

[features]
default = ["start-asm"]
start-asm = []

[dependencies]
log = "0.4.29"
macros = { path = '../../shared/macros' }
constants = { path = '../../shared/constants' }