[package]
name = "sw_uart"
version = "0.1.0"
edition = "2024"

[lib]
name = "sw_uart"
path = "src/lib.rs"

[[bin]]
name = "sw_uart"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
crab-pi = { path = "../crab-pi" }
constants = {path = "../../shared/constants"}