[package]
name = "pi-install"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
serialport = { version = "4.8.1", default-features = false }
constants = {path = "../shared/constants"}
crc32fast = "1.5.0"
