[package]
name = "vector_base"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vector_base"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
crab-pi = { path = "../crab-pi" }